version: '3.8'

services:
  app:
    build: ./
    command: ./birgedo
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - host

  db:
    restart: always
    image: postgres:latest
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5436:5432"
    networks:
      - host
  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./../migrations:/migrations
    networks:
      - host
    command:
      [ "-path", "/migrations", "-database", "postgresql://postgres:postgres@db:5436/postgres?sslmode=disable", "up" ]
networks:
  host:
    name: host
    external: true